image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install -y software-properties-common
  - apt-add-repository ppa:ansible/ansible
  - apt-get update
  - apt-get install -y ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

build:
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook tests/test.yml -i tests/inventory

