---
image: python:2.7

stages:
  - syntax_check
  - build

befor_script:
  - pip install --upgrade pip
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

job1:
  stage: syntax_check
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

