image: python:2.7

stages:
  - check
  - build

before_script:
  - pip install --upgrade pip
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

syntax:
  stage: check
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

dryrun:
  stage: check
  script:
    - ansible-playbook tests/test.yml -i tests/inventory -C

apply:
  stage: build
  script:
    - ansible-playbook tests/test.yml -i tests/inventory

