image: python:2.7

before_script:
  - pip install --upgrade pip
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

build:
  script:
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
    - ansible-playbook tests/test.yml -i tests/inventory

