---
language: python
python: 2.7
sudo: false

addons:
  apt:
    packages:
      - python

before_install:
  - sudo apt-get update
  - sudo apt-get install libgeoip-dev
  - gem update bundler

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -C
  - ansible-playbook tests/test.yml -i tests/inventory
