---
language: python
sudo: true

jobs:
  include:
    - os: linux
      dist: bionic
      language: python
    - os: osx
      osx_image: xcode11.2
      language: generic

addons:
  apt:
    packages:
      - python

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install ansible ;fi

install:
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory