---
# tasks file for ../ansible-devenv-role
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  when: ansible_distribution == "Ubuntu"

- apt_repository:
    repo: "{{ item }}"
  when: ansible_distribution == "Ubuntu"
  with_items:
    - ppa:ansible/ansible
    - ppa:neovim-ppa/stable

- name: Install modules
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  vars:
    packages:
      - git
      - tmux
      - curl
      - zsh
      - make
      - gcc
      - golang
      - software-properties-common
      - ansible
      - neovim
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip

- name: Create cache directory
  file:
    path: "$HOME/.cache/dein"
    state: directory

- name: Download dein.vim installer
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: $HOME/.cache/dein

- name : Install dein.vim
  shell: sh ./installer.sh $HOME/.cache/dein
  args:
    chdir: $HOME/.cache/dein

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  when: ansible_distribution == "Ubuntu"

- name: Download peco
  unarchive:
    src: https://github.com/peco/peco/releases/download/v0.5.3/peco_linux_amd64.tar.gz
    dest: /usr/src
    remote_src: yes

- name: Move peco module
  copy:
    src: /usr/src/peco_linux_amd64/peco
    dest: /usr/local/bin/peco
    mode: 0755
    remote_src: yes

- name: Clone repository
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: "https://github.com/zplug/zplug.git"     , dest: "$HOME/.zplug"   }
    - { url: "https://gitlab.com/Tocyuki/dotfiles.git", dest: "$HOME/dotfiles" }

- name: Create links
  file:
    src: "$HOME/dotfiles/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
  with_items:
    - .zshrc
    - .tmux.conf
    - .vimrc
    - .config

- name: Install ghq
  shell: export GOPATH=$HOME/go && go get github.com/motemen/ghq

- name: Download Docker installer
  shell: curl -fsSL get.docker.com -o get-docker.sh
  args:
    chdir: /usr/src

- name: Install Docker
  shell: sh get-docker.sh
  args:
    chdir: /usr/src
