---
- name: Include tasks for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Include tasks for Mac
  import_tasks: mac.yml
  when: ansible_distribution == "MacOSX"

- name: Include common tasks
  import_tasks: common.yml
