---
# tasks file for ../ansible-devenv-role
- apt_repository:
  ignore_errors: true
    repo: ppa:ansible/ansible

- name: Install common packages
  apt:
    name: "{{ packages_common }}"
    state: latest
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ packages_apt }}"
    state: latest
    update_cache: yes

- name: Install golang
  snap:
    name: go
    channel: 1.12/stable
    classic: yes

- name: Install ghq
  ignore_errors: true
  become: no
  shell: go get github.com/motemen/ghq

- name: Install peco
  become: no
  shell: go get github.com/peco/peco/cmd/peco

- name: Download Docker installer
  shell: curl -fsSL get.docker.com -o get-docker.sh
  args:
    chdir: /usr/src

- name: Install Docker
  shell: sh get-docker.sh
  args:
    chdir: /usr/src

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
