version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/ansible-devenv-role
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            apt-get install -y software-properties-common
            apt-add-repository ppa:ansible/ansible
            apt-get update
            apt-get install -y ansible
      - run:
          name: Check Ansible version
          command: ansible --version
      - run:
          name: Syntax check for Ansible role
          command: ansible-playbook -i tests/inventory tests/test.yml --syntax-check
      - run:
          name: Run Ansible role
          command: ansible-playbook -i tests/inventory tests/test.yml

